### ISSUE TITLE
AssertionError: Rule "disallowTrailingComma" is already registered

### ISSUE THREAD

**Issue by jussi-kalliokoski** [EE/jscs-trailing-comma#3]
After updating to latest JSCS, I get the following error when running JSCS:

```
AssertionError: Rule "disallowTrailingComma" is already registered
```

Removing this from the my JSCS config makes the problem go away but also of course disables the rules I get from this package:

```
  "additionalRules": [
    "node_modules/jscs-trailing-comma/rules/*.js"
  ],
```

**Comment by mzgol** [comment]
Right, JSCS has added a rule named the same as mine. I hope to introduce some of semantics of this rule into JSCS (see https://github.com/jscs-dev/node-jscs/issues/795) when I finally find time so that this package is no longer needed.

But since I see others are depending on this package, I might just change its name in the meantime. `requireTrailingCommas`/`disallowTrailingCommas`? Not sure if it's best to be so close to the official name.

Any ideas? PR would be welcome as well. ;)

**Comment by mzgol** [comment]
Note that if you just need trailing commas everywhere or nowhere then the JSCS built-in rule is enough for you.

**Comment by mzgol** [comment]
Hmm, actually, it might be enough to just remove `requireTrailingComma` & `disallowTrailingComma` for now and leave `{dissallow,require}TrailingCommaIn{Collapsed,Expanded}Literals` as they are.
